### ISSUE TITLE
BSD-3 license not recognized

### ISSUE THREAD

**Issue by louis77** [galdor/github-license-observer#1]
This repository's license is not identified:
https://github.com/microcosm-cc/bluemonday

According to GitHub, the license file can be any of `LICENSE.txt`, `LICENSE.md` or `LICENSE.rst`:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

The license is BSD-3 so I'm not sure why it is not working.

**Comment by pidu** [comment]
Like wise this one... https://github.com/mongodb/mongo-python-driver

It appears that if there is a rendered h2 with contents About (like in this readme) it picks the wrong section of the page to look for the license link.

**Comment by galdor** [comment]
@pidu This one is a different issue, I'm fixing it right now.
