### ISSUE TITLE
License label is displayed in the wrong place and annotation is wrong

### ISSUE THREAD

**Issue by bahmanm** [galdor/github-license-observer#2]
Should I take this seriously? :grinning: 

![image](https://github.com/galdor/github-license-observer/assets/315582/c72fd18d-ca13-4765-9bbf-57cb32777b3d)

**Comment by galdor** [comment]
You are not the only one having the label displayed in the wrong place. I have no idea why it happens since I never witnessed it during development or after installation of the packaged version. I'll try to find what could be wrong when I get the chance.

**Comment by bahmanm** [comment]
@galdor I personally don't mind the placement.  Rather I'm "concerned" w/ the license warning :sweat_smile: 
ISC is after all an open source license, right?

**Comment by galdor** [comment]
I yes you're right I did not even realize.

Something is really wrong because I see the right label here. I'm starting to suspect there is a timing issue. The script is supposed to run when content has finished loading, but GitHub may fill some parts of the page asynchronously. Will look into that.

**Comment by galdor** [comment]
Thank to @adyxax for finding the problem!
