### ISSUE TITLE
The repositories have "Unknown" licenses

### ISSUE THREAD

**Issue by bahmanm** [galdor/github-license-observer#3]
Some repos, eg [Akka](https://github.com/akka/akka), have "Unknown" licneses as per github.  I think a warning/orange should be displayed in those cases.

Your thoughts?

![image](https://github.com/galdor/github-license-observer/assets/315582/421acced-500d-415c-ab1d-9005284da34d)

**Comment by galdor** [comment]
First time I see this, GitHub uses a completely different HTML element when it detects multiple license files. Let me see what I can do.

**Comment by bahmanm** [comment]
Tested the latest release and works as expected :tada:
