### ISSUE TITLE
Annotation are not consistent for certain licenses

### ISSUE THREAD

**Issue by bahmanm** [galdor/github-license-observer#5]
## Wrong annotation

The annotation is wrong for certain licenses. 

License                    |  Example repo             | Screenshot
:-------------------------:|:-------------------------:|:-------------------------:
0BSD | https://github.com/smoltcp-rs/smoltcp | ![image](https://github.com/galdor/github-license-observer/assets/315582/9f17a565-2983-4970-8dea-2b93123ac01e)
zlib | https://github.com/Shirakumo/glfw | ![image](https://github.com/galdor/github-license-observer/assets/315582/8be98e6f-4a17-4c90-adbe-ee7729c7b181)

## Missing annotation
*Originally reported [on lemmy.ml](https://lemmy.ml/comment/3477018)*

The annotation is absent for certain licenses.  So far MIT has been identified to be the case.  This could be related to #3.

For example: https://github.com/rails/rails

![image](https://github.com/galdor/github-license-observer/assets/315582/80d56fde-2b41-4bcd-83eb-75c8de065c39)

**Comment by galdor** [comment]
You are really good at spotting these issues, thank you! I will with this as soon as I get the time.

**Comment by bahmanm** [comment]
I just updated the issue w/ a new license (zlib) and tidied up the layout.

**Comment by galdor** [comment]
Should be fixed on master.

**Comment by bahmanm** [comment]
Let me know when you push the update to the addons so I can test it out.

**Comment by galdor** [comment]
1.0.2 has just been approved :)

**Comment by bahmanm** [comment]
Just tested and works as expected :tada:

**Comment by bahmanm** [comment]
Unfortunately I found a GPLv3 repo which is identified as "not open source" :confused:   [bahmanm/lemmy-meter](https://github.com/bahmanm/lemmy-meter/)

Did you want to reopen this issue or should I create a new one?

![image](https://github.com/galdor/github-license-observer/assets/315582/e2155468-0541-4386-a7c5-a392682d0320)

**Comment by galdor** [comment]
Problem fixed on master, version 1.0.3 released and waiting for validation.
I'm using the license list on opensource.org, but they don't list all SPDX identifiers (e.g. they specify GPL-3.0-only instead of GPL-3.0).

**Comment by bahmanm** [comment]
Confirmed!  Keep it up!

**Comment by bahmanm** [comment]
@galdor Here's another one:  

https://github.com/alacritty/alacritty

![Screenshot 2023-09-27 at 1 29 09 PM](https://github.com/galdor/github-license-observer/assets/315582/d3460cc0-1988-4968-afce-eb3f882abd16)
