### ISSUE TITLE
GPL3 shown as non-oss

### ISSUE THREAD

**Issue by fwilhe2** [galdor/github-license-observer#6]
Hi,

I've just randomly noticed that on [this repo](https://github.com/ansible-ThoTeam/nexus3-oss) gpl 3 is shown as non-oss, I assume this is not intended.

![image](https://github.com/galdor/github-license-observer/assets/52838694/66a8541b-09d6-426d-b054-ac3b1a89fd74)

**Comment by galdor** [comment]
Should be fixed in version 1.0.3 released a couple hours ago. Feel free to reopen this ticket if you see it happening with 1.0.3.
