### ISSUE TITLE
Add support for repositories with multiple licenses

### ISSUE THREAD

**Issue by veer66** [galdor/github-license-observer#7]
[Tauri](https://github.com/tauri-apps/tauri)'s licenses are MIT and Apache 2.0, which I suppose they are open source licenses.

**Comment by galdor** [comment]
Finally found a repository with multiple licenses detected by GitHub. I will see what I can do.

**Comment by veer66** [comment]
Perhaps [espeak-ng](https://github.com/espeak-ng/espeak-ng) is another example. However, I'm not sure whether COPYING.UCD is an open-source license.

![image](https://github.com/galdor/github-license-observer/assets/370688/d0e58d71-80a0-4b41-abf8-632215326e31)

**Comment by borisfaure** [comment]
https://github.com/knsd/daemonize/ is an other one. A lot of rust crates are dual-licensed that way.
